### ISSUE TITLE
Please deploy to a repo

### ISSUE THREAD

**Issue by jacek99** [totalvoidness/FXThreads#1]
Either Maven Central or at least bintray Jcenter:

https://bintray.com/

**Comment by overheadhunter** [comment]
As this source code is available under a permissive license and consists of only a single file, it shouldn't be hard to use it in any project without adding FXThreads as a Maven dependency. Applying for a sonatype account seems to me a bit of an overkill for such a simple project.

Anyway: As the license allows you to do whatever you like, feel free to fork and publish this project on a public repo :smiley:

**Comment by jacek99** [comment]
OK, may try. I was thinking more of JCenter Bintray, it is fairly simple there

**Comment by overheadhunter** [comment]
:+1: Keep me updated on any progress, then I'll add the dependency to the readme file.

**Comment by jitpack-io** [comment]
In the meantime, its also available on: https://jitpack.io/#totalvoidness/FXThreads/c18f02c16b
